---
- name: Configure EC2 instance
  hosts: 172.31.7.108
  remote_user: ubuntu  
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy HTML file
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

