AWSTemplateFormatVersion: "2010-09-09"
Description: "Simple EC2 instance with security group"

Resources:
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow SSH and HTTP inbound traffic"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0" # Allow SSH from anywhere
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0" # Allow HTTP from anywhere

  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-007020fd9c84e18c7" # Replace with your desired AMI ID
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - !Ref MySecurityGroup
      KeyName: "task" # Replace with your key pair name

